services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mobiauto-backend'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USERNAME}'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: